name = "{{BOT_NAME}}"
uuid = "{{UUID}}"
authors = ["Accord.jl Developer"]
version = "0.1.0"

[deps]
Accord = { path = "../../.." }
DotEnv = "f2b01f46-224f-11e9-2b0b-cdbd1d7b2907"
{{EXTRA_DEPS}}

[compat]
julia = "1.10"
