name = "Accord"
uuid = "e32180e5-4c2f-49c0-8021-11dfb7fed3fc"
version = "0.2.0"
authors = ["Accord.jl Contributors"]

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Opus_jll = "91d4177d-7536-5919-b921-800302f37372"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"

[compat]
AbbreviatedStackTraces = "0.1"
Aqua = "0.8"
CodecZlib = "0.7"
Dates = "1"
HTTP = "1"
JET = "0.9, 0.10, 0.11"
JSON3 = "1"
LRUCache = "1"
Logging = "1"
Opus_jll = "1"
PrecompileTools = "1"
ReTestItems = "1"
Sockets = "1"
StructTypes = "1"
Test = "1"
julia = "1.11"
libsodium_jll = "1"

[extras]
AbbreviatedStackTraces = "ac637c84-cc71-43bf-9c33-c1b4316be3d4"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test", "AbbreviatedStackTraces", "ReTestItems"]
