name = "Accord"
uuid = "e32180e5-4c2f-49c0-8021-11dfb7fed3fc"
authors = ["Accord.jl Contributors"]
version = "0.1.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Opus_jll = "91d4177d-7536-5919-b921-800302f37372"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"

[compat]
CodecZlib = "0.7"
HTTP = "1"
JSON3 = "1"
LRUCache = "1"
Opus_jll = "1"
StructTypes = "1"
libsodium_jll = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[targets]
test = ["Test", "Dates"]
