name = "AIChatBot"
uuid = "7c13416a-8923-4c07-b387-5732c4389439"
authors = ["Accord.jl Community"]
version = "0.1.0"

[deps]
Accord = { path = "../../.." }
DotEnv = "f2b01f46-224f-11e9-2b0b-cdbd1d7b2907"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[compat]
julia = "1.10"
