name = "BasicBot"
uuid = "a6876344-9344-4864-b778-633006329753"
authors = ["Accord.jl Community"]
version = "0.1.0"

[deps]
Accord = { path = "../../.." }
DotEnv = "f2b01f46-224f-11e9-2b0b-cdbd1d7b2907"

[compat]
julia = "1.10"
